# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cli.ipynb.

# %% auto 0
__all__ = ['chelp']

# %% ../nbs/00_cli.ipynb 2
from fastcore.script import *

# %% ../nbs/00_cli.ipynb 4
@call_parse
def chelp():
    "Show help for all console scripts"
    from fastcore.xtras import console_help

    console_help("geo2ml")
