project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: syke.scss
    toc: true
    page-layout: full

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]